[package]
name = "orchard"
version = "0.2.0"
authors = [
    "Sean Bowe <sean@electriccoin.co>",
    "Jack Grigg <jack@electriccoin.co>",
    "Daira Hopwood <daira@jacaranda.org>",
    "Ying Tong Lai <yingtong@electriccoin.co>",
    "Kris Nuttycombe <kris@electriccoin.co>",
]
edition = "2021"
rust-version = "1.56.1"
description = "The Orchard shielded transaction protocol"
license-file = "LICENSE-BOSL"
repository = "https://github.com/zcash/orchard"
documentation = "https://docs.rs/orchard"
readme = "README.md"
categories = ["cryptography::cryptocurrencies"]
keywords = ["zcash"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs", "--html-in-header", "katex-header.html"]

[dependencies]
aes = { version = "0.7", default-features = false }
bitvec = { version = "1", default-features = false }
blake2b_simd = { version = "1", default-features = false }
ff = { version = "0.12", default-features = false, features = ["bits"] }
fpe = { version = "0.5", default-features = false, features = ["alloc"] }
group = { version = "0.12", default-features = false }
halo2_gadgets = { git = "https://github.com/jarys/halo2_gadgets", branch = "empty" }
halo2_proofs = { version = "0.2", optional = true }
hex = { version = "0.4", default-features = false }
lazy_static = { version = "1", optional = true }
memuse = { version = "0.2", optional = true, features = ["nonempty"] }
#pasta_curves = { version = "0.4", default-features = false, features = ["alloc", "bits"] }
proptest = { version = "1.0.0", optional = true }
rand = { version = "0.8", default-features = false }
#reddsa = { version = "0.3", default-features = false }
reddsa = { git = "https://github.com/jarys/reddsa", branch="alloc-3-plus", default-features = false }
nonempty = { version = "0.7", optional = true }
serde = { version = "1.0", optional = true, features = ["derive"] }
subtle = { version = "2.3", default-features = false }
#zcash_note_encryption = { version = "0.1", default-features = false }
zcash_note_encryption = { git = "https://github.com/jarys/librustzcash", branch="alloc-3-plus" }
incrementalmerkletree = { version = "0.3", optional = true }

# Logging
tracing = { version = "0.1", optional = true }

# Developer tooling dependencies
plotters = { version = "0.3.0", optional = true }

[dependencies.pasta_curves]
git = "https://github.com/jarys/pasta_curves"
branch = "unboxed-closures"
default-features = false
features = ["bits", "unboxed_closures"]

[dev-dependencies]
criterion = "0.3"
halo2_gadgets = { git = "https://github.com/jarys/halo2_gadgets", branch = "empty" }
hex = "0.4"
proptest = "1.0.0"
#zcash_note_encryption = { version = "0.1", features = ["pre-zip-212"] }

[target.'cfg(unix)'.dev-dependencies]
pprof = { version = "0.9", features = ["criterion", "flamegraph"] } # MSRV 1.56

[lib]
bench = false

[features]
dev-graph = ["halo2_proofs/dev-graph", "plotters", "std"]
test-dependencies = ["std", "proptest"]
default = ["std"]
std = [
    "blake2b_simd/std", # to preserve some gpu optimizations
    "lazy_static",
    "memuse",
    "reddsa/std",
    "nonempty",
    "serde",
    "halo2_proofs",
    "incrementalmerkletree",
    "zcash_note_encryption/alloc",
    "tracing",
]

[[bench]]
name = "note_decryption"
harness = false

[[bench]]
name = "small"
harness = false

[[bench]]
name = "circuit"
harness = false

[profile.release]
debug = true

[profile.bench]
debug = true
